version: '3.8'
services:
  stay-api-postgres:
    image: postgis/postgis:16-3.4
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stay
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  stay-api-redis:
    image: redis
    hostname: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  stay-api-mongo:
    image: mongo:7
    hostname: mongo-server
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: stay_logs
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
  aws:
    image: 'localstack/localstack'
    container_name: 'localstack'
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    ports:
      - '4566:4566'
volumes:
  redis:
    driver: local
  pgdata:
    driver: local
  mongodata:
    driver: local





