version: '3.8'
services:
  stay-api-postgres:
    image: postgis/postgis:16-3.4
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stay
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  stay-api-redis:
    image: redis
    hostname: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  stay-api-mongo:
    image: mongo:7
    hostname: mongo-server
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: stay_logs
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
volumes:
  redis:
    driver: local
  pgdata:
    driver: local
  mongodata:
    driver: local





